all: lab9_part2.c lab9_part3.c lab9_part4.c lab9_part5.c
	gcc -o Part2Executable lab9_part2.c
	gcc -o Part3Executable lab9_part3.c
	gcc -o Part4Executable lab9_part4.c
	gcc -o Part5Executable lab9_part5.c -lpthread

clean:; rm -f *.out Part2Executable Part3Executable Part4Executable Part5Executable